name: Publish Docker image

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # Browserless
      - name: Extract metadata for Docker (browserless)
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: RainEggplant/chatgpt-telegram-bot
          tags: |
            type=semver,pattern={{version}}
      - name: Build and push (browserless)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # Browser-based
      - name: Extract metadata for Docker (browser-based)
        id: meta_browser
        uses: docker/metadata-action@v4
        with:
          images: RainEggplant/chatgpt-telegram-bot
          flavor: |
            suffix=-browser,onlatest=true
          tags: |
            type=semver,pattern={{version}}
      - name: Build and push (browser-based)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.browser
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta_browser.outputs.tags }}
          labels: ${{ steps.meta_browser.outputs.labels }}
